function n(string, fret, beats, pick, tech, group, role, label, finger) {
  var o = { string: string, fret: fret, beats: beats || 0.5, pick: pick || 'D', group: group, role: role || 'line' };
  if (tech && tech.length) o.tech = tech;
  if (label) o.groupLabel = label;
  if (finger) o.finger = finger;
  return o;
}
function chord(group, label, dots, beats) {
  return dots.map(function (d, i) {
    return n(d[0], d[1], i === 0 ? (beats || 2) : 0, 'D', d[2], group, 'chord', i === 0 ? label : null, d[3]);
  });
}

export const SHEET_LESSONS = [
  {
    id: 'sheet-g-phrasing',
    title: 'Improving Phrasing & Melodic Control',
    level: 'intermediate',
    style: 'lead',
    genre: 'any',
    key: 'G',
    bpm: 86,
    track: 'sheet',
    chords: ['G', 'Em', 'C', 'D', 'Am', 'Bm'],
    summary: 'G major two-octave scale, three-notes-per-string, then a G-Em-C-D study with bends and legato.',
    watchFor: 'Even tone. Do not rush the whole-step bend. Alternate pick the scale.',
    goals: [
      'Play G major two octaves with even alternate picking.',
      'Shift to 3NPS without a gap at the position change.',
      'Bend fret 5 to the pitch of fret 7 and land in tune.',
      'Hammer 5 to 7 and pull back to 5 on the high E.'
    ],
    steps: [
      'Warm up G major two octaves at 60 BPM. One note per click.',
      'Play the 3NPS version. Keep three notes on each string.',
      'Study piece at 80 BPM. Make phrases breathe — leave space on long notes.',
      'Isolate the bend (high E 5 to 7) until it matches a fretted 7.',
      'Add hammer-on / pull-off 5-h7-p5. Fingers stay close to the board.'
    ],
    sheet: {
      focus: 'Phrasing, scales, bends, legato, rhythm',
      advice: [
        'Start slow and build accuracy.',
        'Use the in-app metronome.',
        'Record one pass and listen for rushed bends.',
        'Musicality first. Speed last.'
      ]
    },
    notes: [
      n(0, 3, 0.5, 'D', null, 0, 'line', 'G major 2 octaves'),
      n(0, 5, 0.5, 'U', null, 0, 'line'),
      n(1, 2, 0.5, 'D', null, 0, 'line'),
      n(1, 3, 0.5, 'U', null, 0, 'line'),
      n(1, 5, 0.5, 'D', null, 0, 'line'),
      n(2, 2, 0.5, 'U', null, 0, 'line'),
      n(2, 4, 0.5, 'D', null, 0, 'line'),
      n(2, 5, 0.5, 'U', null, 0, 'line'),
      n(3, 2, 0.5, 'D', null, 0, 'line'),
      n(3, 4, 0.5, 'U', null, 0, 'line'),
      n(3, 5, 0.5, 'D', null, 0, 'line'),
      n(4, 3, 0.5, 'U', null, 0, 'line'),
      n(4, 5, 0.5, 'D', null, 0, 'line'),
      n(5, 2, 0.5, 'U', null, 0, 'line'),
      n(5, 3, 0.5, 'D', null, 0, 'line'),
      n(5, 5, 1, 'U', null, 0, 'line'),
      n(5, 3, 0.5, 'D', null, 1, 'line', 'G major 3NPS'),
      n(5, 5, 0.5, 'U', null, 1, 'line'),
      n(5, 7, 0.5, 'D', null, 1, 'line'),
      n(5, 8, 0.5, 'U', null, 1, 'line'),
      n(4, 3, 0.5, 'D', null, 1, 'line'),
      n(4, 5, 0.5, 'U', null, 1, 'line'),
      n(4, 6, 0.5, 'D', null, 1, 'line'),
      n(4, 8, 0.5, 'U', null, 1, 'line'),
      n(3, 4, 0.5, 'D', null, 1, 'line'),
      n(3, 5, 0.5, 'U', null, 1, 'line'),
      n(3, 7, 0.5, 'D', null, 1, 'line'),
      n(2, 4, 0.5, 'U', null, 1, 'line'),
      n(2, 5, 0.5, 'D', null, 1, 'line'),
      n(2, 7, 0.5, 'U', null, 1, 'line'),
      n(1, 5, 0.5, 'D', null, 1, 'line'),
      n(0, 5, 1, 'U', null, 1, 'line'),
      n(1, 5, 1, 'D', null, 2, 'line', 'Study in G'),
      n(1, 0, 0.5, 'D', null, 2, 'line'),
      n(1, 3, 0.5, 'U', null, 2, 'line'),
      n(2, 5, 0.5, 'D', null, 2, 'line'),
      n(3, 0, 0.5, 'U', null, 2, 'line'),
      n(3, 0, 1, 'D', null, 2, 'line'),
      n(5, 8, 0.5, 'D', null, 3, 'line', 'Phrase 2'),
      n(5, 3, 0.5, 'U', null, 3, 'line'),
      n(2, 5, 0.5, 'D', null, 3, 'line'),
      n(5, 6, 0.5, 'U', null, 3, 'line'),
      n(1, 3, 0.5, 'D', null, 3, 'line'),
      n(2, 5, 0.5, 'U', null, 3, 'line'),
      n(5, 9, 0.5, 'D', null, 3, 'line'),
      n(1, 4, 0.5, 'U', null, 3, 'line'),
      n(5, 3, 0.5, 'D', ['B'], 4, 'line', 'Bend 5 to 7'),
      n(5, 7, 1, 'D', null, 4, 'line'),
      n(5, 5, 0.5, 'D', ['H'], 5, 'line', 'Legato 5 h7 p5'),
      n(5, 7, 0.5, 'D', ['P'], 5, 'line'),
      n(5, 5, 1, 'D', null, 5, 'line')
    ]
      .concat(chord(6, 'G', [[0, 3, null, 3], [1, 2, null, 2], [2, 0], [3, 0], [4, 0], [5, 3, null, 4]], 2))
      .concat(chord(7, 'Em', [[0, 0], [1, 2, null, 2], [2, 2, null, 3], [3, 0], [4, 0], [5, 0]], 2))
      .concat(chord(8, 'C', [[1, 3, null, 3], [2, 2, null, 2], [3, 0], [4, 1, null, 1], [5, 0]], 2))
      .concat(chord(9, 'D', [[2, 0], [3, 2, null, 1], [4, 3, null, 3], [5, 2, null, 2]], 2))
  },
  {
    id: 'sheet-int-tech',
    title: 'Intermediate Techniques: Control & Fretboard',
    level: 'intermediate',
    style: 'lead',
    genre: 'rock',
    key: 'C',
    bpm: 85,
    track: 'sheet',
    chords: ['C7'],
    summary: 'Palm-muted alternate picking, open C major, whole-step bends on the A string, C7 arpeggio, then a blues-rock lick.',
    watchFor: 'Relaxed wrist on the warmup. Bend A-string 7 to the pitch of fret 9. Support with the middle finger.',
    goals: [
      'Even alternate picking with palm mute on the low strings.',
      'C major open position ascending and descending.',
      'Whole-step bend A7 to A9 in tune.',
      'Hit C, E, G, Bb of C7 on purpose.',
      'Play the sample lick as one idea, not five separate licks.'
    ],
    steps: [
      'Warmup at 80 BPM, palm mute, two notes per click if needed.',
      'C major open: climb and descend. Root is C on A3, not a mystery 8th-fret claim.',
      'Bend A7 to match a fretted A9. Release smooth.',
      'C7 tones: C (A3), E (D2), G (D5), Bb (A1 / G3).',
      'Sample lick at 85. Add vibrato only after the bend is in tune.'
    ],
    sheet: {
      focus: 'Alternate picking, C major, bends, chord tones',
      advice: [
        'Accuracy before speed.',
        'Record and listen.',
        'Move the same patterns to other keys.',
        'Improvise the lick over a C7 loop.'
      ]
    },
    notes: [
      n(0, 5, 0.5, 'D', ['PM'], 0, 'line', 'Alt pick warmup'),
      n(0, 7, 0.5, 'U', ['PM'], 0, 'line'),
      n(0, 8, 0.5, 'D', ['PM'], 0, 'line'),
      n(0, 8, 0.5, 'U', ['PM'], 0, 'line'),
      n(1, 5, 0.5, 'D', ['PM'], 0, 'line'),
      n(1, 7, 0.5, 'U', ['PM'], 0, 'line'),
      n(1, 8, 0.5, 'D', ['PM'], 0, 'line'),
      n(1, 8, 0.5, 'U', ['PM'], 0, 'line'),
      n(2, 5, 0.5, 'D', ['PM'], 0, 'line'),
      n(2, 7, 0.5, 'U', ['PM'], 0, 'line'),
      n(2, 5, 0.5, 'D', ['PM'], 0, 'line'),
      n(1, 8, 0.5, 'U', ['PM'], 0, 'line'),
      n(1, 7, 0.5, 'D', ['PM'], 0, 'line'),
      n(1, 5, 0.5, 'U', ['PM'], 0, 'line'),
      n(0, 1, 0.5, 'D', null, 1, 'line', 'C major open'),
      n(0, 3, 0.5, 'U', null, 1, 'line'),
      n(0, 5, 0.5, 'D', null, 1, 'line'),
      n(1, 0, 0.5, 'U', null, 1, 'line'),
      n(1, 2, 0.5, 'D', null, 1, 'line'),
      n(1, 3, 0.5, 'U', null, 1, 'line'),
      n(1, 5, 0.5, 'D', null, 1, 'line'),
      n(2, 0, 0.5, 'U', null, 1, 'line'),
      n(2, 2, 0.5, 'D', null, 1, 'line'),
      n(2, 3, 0.5, 'U', null, 1, 'line'),
      n(2, 5, 0.5, 'D', null, 1, 'line'),
      n(3, 0, 0.5, 'U', null, 1, 'line'),
      n(3, 2, 0.5, 'D', null, 1, 'line'),
      n(4, 0, 0.5, 'U', null, 1, 'line'),
      n(4, 1, 0.5, 'D', null, 1, 'line'),
      n(4, 3, 0.5, 'U', null, 1, 'line'),
      n(5, 0, 0.5, 'D', null, 1, 'line'),
      n(5, 1, 0.5, 'U', null, 1, 'line'),
      n(5, 3, 1, 'D', null, 1, 'line'),
      n(0, 5, 0.5, 'D', null, 2, 'line', 'A-string bends'),
      n(0, 6, 0.5, 'U', null, 2, 'line'),
      n(0, 7, 0.5, 'D', null, 2, 'line'),
      n(0, 7, 0.5, 'U', null, 2, 'line'),
      n(1, 5, 0.5, 'D', null, 2, 'line'),
      n(1, 5, 0.5, 'U', null, 2, 'line'),
      n(1, 7, 1, 'D', ['B'], 2, 'line'),
      n(1, 7, 0.5, 'U', null, 2, 'line'),
      n(1, 5, 0.5, 'D', null, 2, 'line'),
      n(1, 5, 0.5, 'U', null, 2, 'line'),
      n(1, 7, 1, 'D', ['B'], 2, 'line'),
      n(0, 1, 1, 'D', null, 3, 'line', 'C7 tones'),
      n(1, 3, 0.5, 'U', null, 3, 'line'),
      n(1, 5, 0.5, 'D', null, 3, 'line'),
      n(2, 2, 0.5, 'U', null, 3, 'line'),
      n(2, 3, 0.5, 'D', null, 3, 'line'),
      n(2, 5, 0.5, 'U', null, 3, 'line'),
      n(1, 5, 0.5, 'D', null, 3, 'line'),
      n(1, 3, 0.5, 'U', null, 3, 'line'),
      n(0, 5, 0.5, 'D', null, 3, 'line'),
      n(0, 3, 1, 'U', null, 3, 'line'),
      n(0, 5, 0.5, 'D', null, 4, 'line', 'Sample lick'),
      n(0, 8, 0.5, 'U', null, 4, 'line'),
      n(1, 5, 0.5, 'D', null, 4, 'line'),
      n(1, 7, 0.5, 'U', null, 4, 'line'),
      n(1, 8, 0.5, 'D', null, 4, 'line'),
      n(1, 8, 0.5, 'U', null, 4, 'line'),
      n(2, 7, 0.5, 'D', null, 4, 'line'),
      n(2, 8, 0.5, 'U', null, 4, 'line'),
      n(2, 10, 0.5, 'D', null, 4, 'line'),
      n(3, 7, 0.5, 'U', null, 4, 'line'),
      n(3, 9, 0.5, 'D', null, 4, 'line'),
      n(3, 10, 0.5, 'U', null, 4, 'line'),
      n(3, 10, 0.5, 'D', null, 4, 'line'),
      n(4, 8, 0.5, 'U', null, 4, 'line'),
      n(4, 10, 0.5, 'D', null, 4, 'line'),
      n(5, 8, 0.5, 'U', null, 4, 'line'),
      n(5, 10, 0.5, 'D', null, 4, 'line'),
      n(5, 10, 1, 'D', ['B'], 4, 'line'),
      n(5, 10, 0.5, 'U', null, 4, 'line'),
      n(5, 8, 0.5, 'D', null, 4, 'line'),
      n(5, 8, 0.5, 'U', null, 4, 'line'),
      n(5, 10, 1, 'D', ['B'], 4, 'line')
    ]
  },
  {
    id: 'sheet-g-tabs',
    title: 'Intermediate Tabs: Scale, Changes, Lick, Groove',
    level: 'intermediate',
    style: 'rhythm',
    genre: 'rock',
    key: 'G',
    bpm: 90,
    track: 'sheet',
    chords: ['Am', 'F', 'C', 'G', 'Em'],
    summary: 'G major on one string, Am-F-C-G arpeggios, A minor pentatonic lick with hammer slide and vibrato, then a palm-muted Em groove.',
    watchFor: 'Connect G major shapes across the neck. Mute on the rest in the Em groove.',
    goals: [
      'Play G major up the A string to fret 15.',
      'Arpeggiate Am F C G instead of only strumming.',
      'Hammer, slide, and vibrato inside the A minor pent lick.',
      'Palm-mute the Em riff and leave the rest silent.'
    ],
    steps: [
      'G major on the A string: 3 5 7 8 7 10 12 10 12 12 15. Alternate pick.',
      'Am arpeggio A0-C1-E2-A3. F: F1-A2-C3-F1. C and G the same idea.',
      'Am pent lick: hammer A5 to 8, climb, slide into 12, vibrato on 15.',
      'Em groove: muted eighths, rest on beat 3, accent the ands.'
    ],
    sheet: {
      focus: 'Scale vocabulary, phrasing, rhythm, dynamics',
      advice: [
        'Metronome first.',
        'One technique at a time.',
        'Make music, not only notes.',
        'Log tempo after each clean pass.'
      ]
    },
    notes: [
      n(1, 3, 0.5, 'D', null, 0, 'line', 'G major A-string'),
      n(1, 5, 0.5, 'U', null, 0, 'line'),
      n(1, 7, 0.5, 'D', null, 0, 'line'),
      n(1, 8, 0.5, 'U', null, 0, 'line'),
      n(1, 7, 0.5, 'D', null, 0, 'line'),
      n(1, 10, 0.5, 'U', null, 0, 'line'),
      n(1, 12, 0.5, 'D', null, 0, 'line'),
      n(1, 10, 0.5, 'U', null, 0, 'line'),
      n(1, 12, 0.5, 'D', null, 0, 'line'),
      n(1, 12, 0.5, 'U', null, 0, 'line'),
      n(1, 15, 2, 'D', null, 0, 'line'),
      n(1, 0, 0.5, 'D', null, 1, 'line', 'Am arpeggio'),
      n(2, 2, 0.5, 'U', null, 1, 'line'),
      n(3, 2, 0.5, 'D', null, 1, 'line'),
      n(4, 1, 0.5, 'U', null, 1, 'line'),
      n(1, 1, 0.5, 'D', null, 2, 'line', 'F arpeggio'),
      n(2, 3, 0.5, 'U', null, 2, 'line'),
      n(3, 2, 0.5, 'D', null, 2, 'line'),
      n(4, 1, 0.5, 'U', null, 2, 'line'),
      n(5, 1, 0.5, 'D', null, 2, 'line'),
      n(2, 2, 0.5, 'D', null, 3, 'line', 'C arpeggio'),
      n(3, 0, 0.5, 'U', null, 3, 'line'),
      n(4, 1, 0.5, 'D', null, 3, 'line'),
      n(5, 0, 0.5, 'U', null, 3, 'line'),
      n(2, 0, 0.5, 'D', null, 4, 'line', 'G arpeggio'),
      n(3, 0, 0.5, 'U', null, 4, 'line'),
      n(4, 0, 0.5, 'D', null, 4, 'line'),
      n(5, 3, 1, 'U', null, 4, 'line'),
      n(1, 5, 0.5, 'D', ['H'], 5, 'line', 'Am pent lick'),
      n(1, 8, 0.5, 'D', null, 5, 'line'),
      n(1, 10, 0.5, 'U', null, 5, 'line'),
      n(1, 12, 1, 'D', null, 5, 'line'),
      n(1, 5, 0.5, 'D', null, 5, 'line'),
      n(1, 8, 0.5, 'U', null, 5, 'line'),
      n(1, 12, 0.5, 'D', null, 5, 'line'),
      n(2, 12, 0.5, 'U', null, 5, 'line'),
      n(1, 5, 0.5, 'D', ['H'], 5, 'line'),
      n(1, 10, 0.5, 'U', null, 5, 'line'),
      n(1, 12, 0.5, 'D', ['S'], 5, 'line'),
      n(1, 14, 0.5, 'D', ['P'], 5, 'line'),
      n(1, 12, 0.5, 'U', ['S'], 5, 'line'),
      n(1, 15, 1.5, 'D', ['~'], 5, 'line'),
      n(3, 0, 0.5, 'D', ['PM'], 6, 'line', 'Em mute groove'),
      n(3, 0, 0.5, 'U', ['PM'], 6, 'line'),
      n(3, 0, 0.5, 'D', ['PM'], 6, 'line'),
      n(3, 0, 0.5, 'U', ['PM'], 6, 'line'),
      n(3, 0, 0.5, 'D', ['PM'], 6, 'line'),
      n(3, 0, 0.5, 'U', ['PM'], 6, 'line'),
      n(3, 0, 0.5, 'D', ['PM'], 6, 'line'),
      n(3, 0, 0.5, 'U', ['PM'], 6, 'line')
    ]
      .concat(chord(7, 'Em', [[0, 0], [1, 2, null, 2], [2, 2, null, 3], [3, 0], [4, 0], [5, 0]], 2))
  }
];
